0.84.0 (patches unapplied)
Imported using git-ubuntu import.

diff --git a/debian/tests/unshare-qemuwrapper b/debian/tests/unshare-qemuwrapper
--- a/debian/tests/unshare-qemuwrapper
+++ b/debian/tests/unshare-qemuwrapper
@@ -25,7 +25,21 @@
 set -exu
 
 EXTRA_DEPS=gnupg,sbuild,mmdebstrap,build-essential,uidmap,fakeroot,diffoscope,devscripts
+PORT=$(python3 -c 'from socket import socket; s=socket(); s.bind(("", 0)); print(s.getsockname()[1]);' || echo 10022)
 SCRIPT=./debian/tests/unshare
+
+. /etc/os-release
+release=${VERSION_CODENAME:-unstable}
+
+if [ "$ID" = ubuntu ]; then
+	COMPONENTS=main,universe
+	KERNEL_PACKAGE=linux-image-kvm
+	KERNEL_PATH=/boot
+else
+	COMPONENTS=main
+	KERNEL_PACKAGE=linux-image-cloud-amd64
+	KERNEL_PATH=
+fi
 
 [ -e debian/tests/control ]
 SOURCES="$(pwd)"
@@ -33,7 +47,7 @@ SOURCES="$(pwd)"
 if [ -z ${AUTOPKGTEST_TMP+x} ]; then
 	# if AUTOPKGTEST_TMP is not set, then this script is probably not
 	# executed under autopkgtest
-	TMPDIR=$(mktemp --directory)
+	TMPDIR=$(mktemp --directory --tmpdir sbuild.XXXXXXXXXX)
 	aptsources=
 	MODE=auto
 else
@@ -52,8 +66,8 @@ else
 	fi
 	for f in /etc/apt/sources.list.d/*.list /etc/apt/sources.list.d/*.sources; do
 		[ -e "$f" ] || continue
-		sed -i 's/ file:\/\// copy:\/\//' $f
-		cat $f
+		sed -i 's/ file:\/\// copy:\/\//' "$f"
+		cat "$f"
 		aptsources="$aptsources $f"
 	done
 	MODE=root
@@ -93,8 +107,8 @@ default linux
 timeout 0
 
 label linux
-kernel /vmlinuz
-append initrd=/initrd.img root=/dev/vda1 net.ifnames=0 console=ttyS0
+kernel $KERNEL_PATH/vmlinuz
+append initrd=$KERNEL_PATH/initrd.img root=/dev/vda1 net.ifnames=0 console=ttyS0
 END
 
 # network interface config
@@ -109,7 +123,7 @@ iface eth0 inet dhcp
 END
 
 # copy in the public key
-mkdir "\$rootfs/root/.ssh"
+mkdir -p "\$rootfs/root/.ssh"
 cp "$TMPDIR/id_rsa.pub" "\$rootfs/root/.ssh/authorized_keys"
 chroot "\$rootfs" chown 0:0 /root/.ssh/authorized_keys
 
@@ -137,17 +151,18 @@ done
 SCRIPT
 chmod +x "$TMPDIR/setup.sh"
 
-if [ ! -e "$TMPDIR/debian-unstable-host.tar" ]; then
+if [ ! -e "$TMPDIR/${ID}-${release}-host.tar" ]; then
+# shellcheck disable=SC2086
 mmdebstrap --variant=apt --mode=$MODE --verbose \
 	--setup-hook="$TMPDIR/setup.sh" \
-	--include=openssh-server,systemd-sysv,ifupdown,netbase,isc-dhcp-client,udev,policykit-1,linux-image-amd64,$EXTRA_DEPS \
-	--customize-hook="$TMPDIR/customize.sh" \
-	unstable "$TMPDIR/debian-unstable-host.tar" $aptsources
+	--include=openssh-server,systemd-sysv,e2fsprogs,ifupdown,initramfs-tools,netbase,isc-dhcp-client,udev,policykit-1,$KERNEL_PACKAGE,$EXTRA_DEPS \
+	--customize-hook="$TMPDIR/customize.sh" --components="$COMPONENTS" \
+	"${release}" "$TMPDIR/${ID}-${release}-host.tar" $aptsources
 fi
 
 # use guestfish to prepare the host system
 #
-#  - create a single 2G partition and unpack the rootfs tarball into it
+#  - create a single 4G partition and unpack the rootfs tarball into it
 #  - put a syslinux MBR into the first 440 bytes of the drive
 #  - install extlinux and make partition bootable
 #
@@ -155,11 +170,11 @@ fi
 #   LIBGUESTFS_BACKEND_SETTINGS=force_tcg
 #   libguestfs-test-tool || true
 #   export LIBGUESTFS_DEBUG=1 LIBGUESTFS_TRACE=1
-guestfish -N "$TMPDIR/host.img"=disk:2G -- \
+guestfish -N "$TMPDIR/host.img"=disk:4G -- \
 	part-disk /dev/sda mbr : \
 	mkfs ext2 /dev/sda1 : \
 	mount /dev/sda1 / : \
-	tar-in "$TMPDIR/debian-unstable-host.tar" / : \
+	tar-in "$TMPDIR/${ID}-${release}-host.tar" / : \
 	mkdir /build : \
 	copy-in "$SOURCES/." /build/ : \
 	upload /usr/lib/SYSLINUX/mbr.bin /mbr.bin : \
@@ -180,7 +195,7 @@ guestfish -N "$TMPDIR/host.img"=disk:2G -- \
 # this also multiplexes the console and the monitor to stdio
 # creates a multiplexed stdio backend connected to the serial port and the qemu
 # monitor
-# redirect tcp connections on port 10022 localhost to the host system port 22
+# redirect tcp connections on port $PORT localhost to the host system port 22
 # redirect all output to a file
 # run in the background
 qemu-system-x86_64 \
@@ -191,7 +206,7 @@ qemu-system-x86_64 \
 	-net nic,model=virtio \
 	-nographic \
 	-serial mon:stdio \
-	-net user,hostfwd=tcp:127.0.0.1:10022-:22 \
+	-net "user,hostfwd=tcp:127.0.0.1:$PORT-:22" \
 	-drive file="$TMPDIR/host.img",format=raw,if=virtio \
 	> "$TMPDIR/qemu.log" </dev/null 2>&1 &
 
@@ -200,7 +215,7 @@ QEMUPID=$!
 
 onerror() {
 	# attempt poweroff
-	$ssh -o ConnectTimeout=$TIMEOUT root@localhost systemctl poweroff || true
+	$ssh -o ConnectTimeout="$TIMEOUT" root@localhost systemctl poweroff || true
 	# give a few seconds for poweroff
 	sleep 10
 	kill $QEMUPID || true
@@ -212,7 +227,7 @@ onerror() {
 	echo
 	echo "to test yourself, run qemu with:"
 	echo
-	echo "    $ qemu-system-x86_64 -no-user-config -m 1G -net nic,model=virtio -nographic -serial mon:stdio -net user,hostfwd=tcp:127.0.0.1:10022-:22 -drive file=\"$TMPDIR/host.img\",format=raw,if=virtio"
+	echo "    $ qemu-system-x86_64 -no-user-config -m 1G -net nic,model=virtio -nographic -serial mon:stdio -net user,hostfwd=tcp:127.0.0.1:$PORT-:22 -drive file=\"$TMPDIR/host.img\",format=raw,if=virtio"
 	echo
 	echo "and log in using:"
 	echo
@@ -229,13 +244,13 @@ onerror() {
 }
 
 # show the log and kill qemu in case the script exits first
-trap "cat --show-nonprinting $TMPDIR/qemu.log; onerror" EXIT
+trap 'cat --show-nonprinting "$TMPDIR/qemu.log"; onerror' EXIT
 
 # the default ssh command does not store known hosts and even ignores host keys
 # it identifies itself with the rsa key generated above
 # pseudo terminal allocation is disabled or otherwise, programs executed via
 # ssh might wait for input on stdin of the ssh process
-ssh="ssh -oUserKnownHostsFile=/dev/null -oStrictHostKeyChecking=no -i "$TMPDIR/id_rsa" -T -p 10022"
+ssh="ssh -oPasswordAuthentication=no -oUserKnownHostsFile=/dev/null -oStrictHostKeyChecking=no -i "$TMPDIR/id_rsa" -T -p $PORT"
 
 # we use sleepenh to make sure that we wait the right number of seconds
 # independent on how long the command took beforehand
@@ -252,7 +267,7 @@ while true; do
 	# and we break out of the loop
 	[ $rv -eq 0 ] && break
 	# if the command before took less than $TIMEOUT seconds, wait the remaining time
-	TIMESTAMP=$(sleepenh $TIMESTAMP $TIMEOUT || [ $? -eq 1 ]);
+	TIMESTAMP=$(sleepenh "$TIMESTAMP" $TIMEOUT || [ $? -eq 1 ]);
 	# increment the counter and break out of the loop if we tried
 	# too often
 	i=$((i+1))
@@ -277,7 +292,8 @@ $ssh root@localhost systemctl poweroff || true
 wait $QEMUPID
 
 # cleanup
-for f in debian-unstable-host.tar id_rsa id_rsa.pub \
+[ -e "$TMPDIR/.guestfs-$(id -u)" ] && rm -r "$TMPDIR/.guestfs-$(id -u)"
+for f in "${ID}-${release}-host.tar" id_rsa id_rsa.pub \
 	qemu.log host.img customize.sh setup.sh; do
 	rm "$TMPDIR/$f"
 done
